apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-initial-delay
spec:
  containers:
    - name: kubia
      image: luksa/kubia-unhealthy
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15