apiVersion: v1
kind: Pod
metadata:
    # namespace: custom-namespace
    name: kubia
spec:
    containers:
    - image: luksa/kubia
      name: kubia
      ports:
      - containerPort: 8080
        protocol: TCP  